site_name: APIDocs

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md

  - Core Concepts:
      - Authentication and authorization: core-concepts/authentication-and-authorization.md
      - Common Error Responses and their Solutions: core-concepts/common-error-responses-and-their-solutions.md

  - Guides:
      - Docs Creation:
          - Overview: guides/docs-creation/overview.md
          - Create a new doc: guides/docs-creation/create-a-new-doc.md
          - Retrieve a list of docs by external ID: guides/docs-creation/retrieve-list-of-docs-by-external-id.md
          - Retrieve Doc details by Doc ID: guides/docs-creation/retrieve-doc-details-by-doc-id.md
          - Update Doc Status: guides/docs-creation/update-doc-status.md
          - List Doc contents and expiring content by Docs ID: guides/docs-creation/list-doc-content-and-expiring-content-by-doc-ID.md

      - Docs Update via Lists:
          - Overview: guides/docs-update-via-lists/overview.md
          - Add Lists through Relists or Content Migration: guides/docs-update-via-lists/add-lists-through-relists-or-content-migration.md
          - Retrieve Doc details by external ID: guides/docs-update-via-lists/retrieve-doc-details-by-external-ID.md
          - Retrieve Doc details by Docs ID: guides/docs-update-via-lists/retrieve-doc-details-by-doc-ID.md
          - Cancel a Specific Doc: guides/docs-update-via-lists/cancel-a-specific-doc.md

  - API Reference:
      - Docs:
          - Create: api/docs/create.md
          - List by External ID: api/docs/list-by-external-id.md
          - Get by ID: api/docs/get-by-id.md
          - Update Status: api/docs/update-status.md
          - List Content: api/docs/list-content.md

      - Lists:
          - Add Lists: api/lists/add-lists.md
          - Get Details (External ID): api/lists/get-details-external-id.md
          - Get Details (Doc ID): api/lists/get-details-doc-id.md
          - Cancel Doc: api/lists/cancel-doc.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false

plugins:
  - search
  - awesome-pages
  - glightbox
  - minify:
      minify_html: true
  - redirects
  - section-index
