site_name: APIDocs
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Authentication and authorization: authentication-and-authorization.md
  - Docs Creation and Management APIs: docs-creation-and-management.md
    - Create a new doc: docs-creation-and-management.md
