site_name: APIDocs

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md

  - Core Concepts:
      - Authentication and authorization: core-concepts/authentication-and-authorization.md
      - Common Error Responses and their Solutions: core-concepts/common-error-responses-and-their-solutions.md

  - Guides:
      - Docs Creation:
          - Overview: guides/docs-creation/overview.md
          - Create a new doc: guides/docs-creation/create-a-new-doc.md
          - List Doc contents and expiring content by Docs ID: guides/docs-creation/list-doc-content-and-expiring-content-by-doc-ID.md
          - Retrieve Doc details by Doc ID: guides/docs-creation/retrieve-doc-details-by-doc-id.md
          - Update Doc Status: guides/docs-creation/update-doc-status.md

      - Docs Update via Lists:
          - Overview: guides/docs-update-via-lists/overview.md
          - Add Lists through Relists or Content Migration: guides/docs-update-via-lists/add-lists-through-relists-or-content-migration.md
          - Cancel a Specific Doc: guides/docs-update-via-lists/cancel-a-specific-doc.md

  - API Reference:
      - Introduction: api-reference/index.md
      - Reference: api-reference/reference.md
      - Docs:
          - Create a new Doc: api-reference/docs/docs-create/docs-create.md
          - List doc content and expiring content by doc ID: api-reference/docs/docs-create/docs-contents-list-by-doc-id.md
          - Retrieve doc details by doc ID: api-reference/docs/docs-create/docs-details-retrieve-by-doc-id.md
          - Update Doc Status: api-reference/docs/docs-create/docs-status-update.md

      - Lists:
          - Add Lists through Relists or Content Migration: api-reference/docs/lists-update/lists-add-relists-content-migration.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false

plugins:
  - search
  - swagger:
      swagger_file: docs/api/openapi.yaml
  - awesome-pages
  - glightbox
  - minify:
      minify_html: true
  - redirects
  - section-index
